//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1714mscheck2H
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trip()
        {
            this.Returns = new HashSet<Return>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateOfTakeOff { get; set; }
        public System.TimeSpan TimeOfTakeOff { get; set; }
    
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Return> Returns { get; set; }
        public virtual Person Manger { get; set; }
        public virtual Person CrewMember1 { get; set; }
        public virtual Person CrewMember2 { get; set; }
        public virtual Person Driver { get; set; }
        public virtual Group Group { get; set; }
    }
}
