//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1714mscheck2H
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TripModelContainer : DbContext
    {
        public TripModelContainer()
            : base("name=TripModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<Return> Returns { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
    }
}
